#nullable enable
//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具產生。
//     執行階段版本:4.0.30319.42000
//
//     對此檔案之變更可能導致不正確行為，且若重新產生程式碼，
//     將覆寫這些變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursorTestApp.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
/// 強型別資源存取類別。字串一律使用 Resources.XXX，勿寫死在 XAML / Code。
/// </summary>
public static class Resources
{
    private static readonly ResourceManager ResourceManager =
        new("CursorTestApp.Resources.Resources", typeof(Resources).Assembly);

    /// <summary>
    /// 依鍵名取得字串，使用指定文化。若未指定則使用目前 UICulture。
    /// </summary>
    public static string GetString(string key, CultureInfo? culture = null)
    {
        return ResourceManager.GetString(key, culture ?? CultureInfo.CurrentUICulture) ?? key;
    }

    /// <summary>
    /// 應用程式顯示名稱（範例鍵，後續 Phase 可擴充）
    /// </summary>
    public static string AppName => GetString("AppName");
}
